package com.day_28.station.cxfservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-01-21T16:29:46.166+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://cxfService.station.day_28.com/", name = "ITicketCXFService")
@XmlSeeAlso({ObjectFactory.class})
public interface ITicketCXFService {

    @WebMethod
    @RequestWrapper(localName = "lockTicket", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.LockTicket")
    @ResponseWrapper(localName = "lockTicketResponse", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.LockTicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String lockTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "buyTicket", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.BuyTicket")
    @ResponseWrapper(localName = "buyTicketResponse", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.BuyTicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String buyTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "queryAllTicket", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.QueryAllTicket")
    @ResponseWrapper(localName = "queryAllTicketResponse", targetNamespace = "http://cxfService.station.day_28.com/", className = "com.day_28.station.cxfservice.QueryAllTicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.day_28.station.cxfservice.Ticket> queryAllTicket();
}
