package com.day_28.station.cxfservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-01-21T16:29:46.275+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ITicketCXFServiceService", 
                  wsdlLocation = "http://localhost:8080/ws/ticket?wsdl",
                  targetNamespace = "http://cxfService.station.day_28.com/") 
public class ITicketCXFServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxfService.station.day_28.com/", "ITicketCXFServiceService");
    public final static QName ITicketCXFServicePort = new QName("http://cxfService.station.day_28.com/", "ITicketCXFServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/ticket?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ITicketCXFServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/ticket?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ITicketCXFServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ITicketCXFServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITicketCXFServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITicketCXFServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITicketCXFServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITicketCXFServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ITicketCXFService
     */
    @WebEndpoint(name = "ITicketCXFServicePort")
    public ITicketCXFService getITicketCXFServicePort() {
        return super.getPort(ITicketCXFServicePort, ITicketCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITicketCXFService
     */
    @WebEndpoint(name = "ITicketCXFServicePort")
    public ITicketCXFService getITicketCXFServicePort(WebServiceFeature... features) {
        return super.getPort(ITicketCXFServicePort, ITicketCXFService.class, features);
    }

}
